<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Patient.aspx.cs" Inherits="ClinicManagementApp.Patient" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

    <asp:ScriptManager ID="ScriptManagerPatient" runat="server"></asp:ScriptManager>

    <ajaxToolkit:TabContainer ID="TabContainerPatient" runat="server" ActiveTabIndex="1" class="mb-3">

        <ajaxToolkit:TabPanel ID="TabPanelView" runat="server" HeaderText="View" class="tabPanel">

            <ContentTemplate>

                <asp:GridView ID="GridView_Patient" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" Width="100%">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                    <Columns>
                        <asp:TemplateField HeaderText="PatientID">
                            <ItemTemplate>
                                <asp:Label ID="Label_PatientID" runat="server" Text='<%# Bind("patientID") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Name">
                            <ItemTemplate>
                                <asp:Label ID="Label_Name" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="City">
                            <ItemTemplate>
                                <asp:Label ID="Label_City" runat="server" Text='<%# Bind("city") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Gender">
                            <ItemTemplate>
                                <asp:Label ID="Label_Gender" runat="server" Text='<%# Bind("gender") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Contact">
                            <ItemTemplate>
                                <asp:Label ID="Label_Contact" runat="server" Text='<%# Bind("contact") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="RegistrationDate">
                            <ItemTemplate>
                                <asp:Label ID="Label_RegistrationDate" runat="server" Text='<%# Bind("registrationDate") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                </asp:GridView>

            </ContentTemplate>

        </ajaxToolkit:TabPanel>

        <ajaxToolkit:TabPanel ID="TabPanelAdd" runat="server" HeaderText="Add" class="tabPanel">

            <ContentTemplate>

                <div class="font">
                    <div class="centerAll">
                        <div class="addClinic">

                            <div class="mb-3 text-center">
                                <h5>Add Patient Details</h5>
                            </div>

                            <div class="px-4">


                                <div class="mb-1 row">
                                    <asp:Label ID="Label_Name" runat="server" Text="Name : " class="col-sm-3 col-form-label"></asp:Label>
                                    <div class="col">
                                        <asp:TextBox ID="TextBox_Name" runat="server" type="text" placeholder="Enter Name" class="form-control"></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator_Name" runat="server" ErrorMessage="Please Enter Name" ControlToValidate="TextBox_Name" ForeColor="Red"></asp:RequiredFieldValidator>
                                        <asp:RegularExpressionValidator ID="RegularExpressionValidator_Name" runat="server" ErrorMessage="Only Characters Allowed" ControlToValidate="TextBox_Name" ValidationExpression="^[a-zA-Z]+$" ForeColor="Red"></asp:RegularExpressionValidator>
                                    </div>
                                </div>

                                <div class="mb-4 row">
                                    <asp:Label ID="Label_Address" runat="server" Text="Address : " class="col-sm-3 col-form-label"></asp:Label>
                                    <div class="col">
                                        <asp:TextBox ID="TextBox_Address" runat="server" type="text" placeholder="Enter Address" class="form-control" TextMode="MultiLine"></asp:TextBox>
                                    </div>
                                </div>

                                <div class="mb-4 row">
                                    <asp:Label ID="Label_Area" runat="server" Text="Area : " class="col-sm-3 col-form-label"></asp:Label>
                                    <div class="col">
                                        <asp:TextBox ID="TextBox_Area" runat="server" type="text" placeholder="Enter Area" class="form-control"></asp:TextBox>
                                    </div>
                                </div>

                                <div class="mb-1 row">
                                    <asp:Label ID="Label_City" runat="server" Text="City : " class="col-sm-3 col-form-label"></asp:Label>
                                    <div class="col">
                                        <asp:TextBox ID="TextBox_City" runat="server" type="text" placeholder="Enter City" class="form-control"></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator_City" runat="server" ErrorMessage="Please Enter City" ControlToValidate="TextBox_City" ForeColor="Red"></asp:RequiredFieldValidator>
                                    </div>
                                </div>

                                <div class="mb-4 row">
                                    <asp:Label ID="Label_Pincode" runat="server" Text="Pincode : " class="col-sm-3 col-form-label"></asp:Label>
                                    <div class="col">
                                        <asp:TextBox ID="TextBox_Pincode" runat="server" type="number" placeholder="Enter Pincode" class="form-control" TextMode="Number"></asp:TextBox>
                                    </div>
                                </div>

                                <div class="mb-1 row">
                                    <asp:Label ID="Label_Gender" runat="server" Text="Gender : " class="col-sm-3 col-form-label"></asp:Label>
                                    <div class="col">
                                        <asp:DropDownList ID="DropDownList_Gender" runat="server" placeholder="Select Gender" class="form-control">
                                            <asp:ListItem>Male</asp:ListItem>
                                            <asp:ListItem>Female</asp:ListItem>
                                            <asp:ListItem>Other</asp:ListItem>
                                        </asp:DropDownList>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator_Gender" runat="server" ErrorMessage="Please Enter Gender" ControlToValidate="DropDownList_Gender" ForeColor="Red"></asp:RequiredFieldValidator>
                                    </div>
                                </div>

                                <div class="mb-4 row">
                                    <asp:Label ID="Label_DOB" runat="server" Text="Date of Birth : " class="col-sm-3 col-form-label"></asp:Label>
                                    <div class="col">
                                        <asp:TextBox ID="TextBox_DOB" runat="server" type="date" placeholder="Enter Date of Birth" class="form-control" TextMode="Date"></asp:TextBox>
                                    </div>
                                </div>

                                <div class="mb-1 row">
                                    <asp:Label ID="Label_Contact" runat="server" Text="Contact : " class="col-sm-3 col-form-label"></asp:Label>
                                    <div class="col">
                                        <asp:TextBox ID="TextBox_Contact" runat="server" type="number" placeholder="Enter Contact" class="form-control" TextMode="Number"></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator_Contact" runat="server" ErrorMessage="Please Enter Contact" ControlToValidate="TextBox_Contact" ForeColor="Red"></asp:RequiredFieldValidator>
                                        <asp:RegularExpressionValidator ID="RegularExpressionValidator_Contact" runat="server" ErrorMessage="Please Enter Valid Contact" ControlToValidate="TextBox_Contact" ValidationExpression="^[987]{1}[0-9]{9}$" ForeColor="Red"></asp:RegularExpressionValidator>
                                    </div>
                                </div>

                                <div class="mb-1 row">
                                    <asp:Label ID="Label_Email" runat="server" Text="Email : " class="col-sm-3 col-form-label"></asp:Label>
                                    <div class="col">
                                        <asp:TextBox ID="TextBox_Email" runat="server" type="email" placeholder="Enter Email" class="form-control" TextMode="Email"></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator_Email" runat="server" ErrorMessage="Please Enter Email" ControlToValidate="TextBox_Email" ForeColor="Red"></asp:RequiredFieldValidator>
                                        <asp:RegularExpressionValidator ID="RegularExpressionValidator_Email" runat="server" ErrorMessage="Please Enter Valid Email" ControlToValidate="TextBox_Email" ValidationExpression="^[a-z]+[0-9_]*[a-z]+@[a-z]+\.[a-z]{2,3}$" ForeColor="Red"></asp:RegularExpressionValidator>
                                    </div>
                                </div>

                                <div class="mb-4 row">
                                    <asp:Label ID="Label_Reference" runat="server" Text="Reference From : " class="col-sm-3 col-form-label"></asp:Label>
                                    <div class="col">
                                        <asp:TextBox ID="TextBox_Reference" runat="server" type="text" placeholder="Enter Reference" class="form-control"></asp:TextBox>
                                    </div>
                                </div>

                                <div class="mb-4 row">
                                    <asp:Label ID="Label_BloodGroup" runat="server" Text="Blood Group : " class="col-sm-3 col-form-label"></asp:Label>
                                    <div class="col">
                                        <asp:DropDownList ID="DropDownList_BloodGroup" runat="server" placeholder="Select Blood Group" class="form-control">
                                            <asp:ListItem>A+</asp:ListItem>
                                            <asp:ListItem>B+</asp:ListItem>
                                            <asp:ListItem>AB+</asp:ListItem>
                                            <asp:ListItem>O+</asp:ListItem>
                                            <asp:ListItem>A-</asp:ListItem>
                                            <asp:ListItem>B-</asp:ListItem>
                                            <asp:ListItem>AB-</asp:ListItem>
                                            <asp:ListItem>O-</asp:ListItem>
                                        </asp:DropDownList>
                                    </div>
                                </div>

                                <div class="mb-1 row">
                                    <asp:Label ID="Label_Registration" runat="server" Text="Registration Date : " class="col-sm-3 col-form-label"></asp:Label>
                                    <div class="col">
                                        <asp:TextBox ID="TextBox_Registration" runat="server" type="date" placeholder="Select Registration Date" class="form-control" TextMode="Date"></asp:TextBox>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator_Registration" runat="server" ErrorMessage="Select Registration Date" ControlToValidate="TextBox_Registration" ForeColor="Red"></asp:RequiredFieldValidator>
                                    </div>
                                </div>

                            </div>

                            <div class="mb-3 text-center">
                                <asp:Button ID="Button_Save" runat="server" Text="Save" class="btn btn-primary mx-2" OnClick="Button_Save_Click" />
                                <asp:Button ID="Button_Clear" runat="server" Text="Clear" class="btn btn-primary mx-2" />
                            </div>

                        </div>
                    </div>

                    <ajaxToolkit:TabContainer ID="TabContainerPatientMoreDetails" runat="server" ActiveTabIndex="0" class="mb-3">

                        <ajaxToolkit:TabPanel ID="TabPanelAllergy" runat="server" HeaderText="Allergy" class="tabPanel">

                            <ContentTemplate>

                                <asp:GridView ID="GridViewAllergy" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" ShowFooter="True" Width="100%" ShowHeaderWhenEmpty="true">
                                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                                    <Columns>
                                        <asp:TemplateField HeaderText="Allergy Name">
                                            <EditItemTemplate>
                                                <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
                                            </EditItemTemplate>
                                            <FooterTemplate>
                                                <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
                                            </FooterTemplate>
                                            <ItemTemplate>
                                                <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                        <asp:TemplateField HeaderText="Start Date">
                                            <EditItemTemplate>
                                                <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
                                            </EditItemTemplate>
                                            <FooterTemplate>
                                                <asp:TextBox ID="TextBox4" runat="server"></asp:TextBox>
                                                <asp:Button ID="Button1" runat="server" Text="Button" />
                                            </FooterTemplate>
                                            <ItemTemplate>
                                                <asp:Label ID="Label2" runat="server" Text="Label"></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>
                                    </Columns>
                                    <EditRowStyle BackColor="#999999" />
                                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                                </asp:GridView>

                            </ContentTemplate>

                        </ajaxToolkit:TabPanel>

                        <ajaxToolkit:TabPanel ID="TabPanelChronic" runat="server" HeaderText="Chronic Diesase" class="tabPanel">

                            <ContentTemplate>

                                <asp:GridView ID="GridViewChronic" runat="server"></asp:GridView>

                            </ContentTemplate>

                        </ajaxToolkit:TabPanel>

                        <ajaxToolkit:TabPanel ID="TabPanelMedication" runat="server" HeaderText="Medication History" class="tabPanel">

                            <ContentTemplate>

                                <asp:GridView ID="GridViewMedication" runat="server"></asp:GridView>

                            </ContentTemplate>

                        </ajaxToolkit:TabPanel>

                    </ajaxToolkit:TabContainer>

                </div>

            </ContentTemplate>

        </ajaxToolkit:TabPanel>

    </ajaxToolkit:TabContainer>


</asp:Content>
